//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopCRM.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetShopCRM.Web.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clínica cadastrada com sucesso..
        /// </summary>
        public static string ClinicAddSucess {
            get {
                return ResourceManager.GetString("ClinicAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clínica apagada com sucesso..
        /// </summary>
        public static string ClinicDeleteSucess {
            get {
                return ResourceManager.GetString("ClinicDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clínica atualizada com sucesso..
        /// </summary>
        public static string ClinicUpdateSucess {
            get {
                return ResourceManager.GetString("ClinicUpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha para envio de e-mail não configurado..
        /// </summary>
        public static string EmailPasswordNotFound {
            get {
                return ResourceManager.GetString("EmailPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remetente de e-mail não configurado..
        /// </summary>
        public static string EmailSenderNotFound {
            get {
                return ResourceManager.GetString("EmailSenderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail enviado com sucesso..
        /// </summary>
        public static string EmailSuccess {
            get {
                return ResourceManager.GetString("EmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário e senha para envio de e-mail não configurado..
        /// </summary>
        public static string EmailUserAndPasswordNotFound {
            get {
                return ResourceManager.GetString("EmailUserAndPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário para envio de e-mail não configurado..
        /// </summary>
        public static string EmailUserNotFound {
            get {
                return ResourceManager.GetString("EmailUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tutor cadastrado com sucesso..
        /// </summary>
        public static string GuardianAddSucess {
            get {
                return ResourceManager.GetString("GuardianAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tutor apagado com sucesso..
        /// </summary>
        public static string GuardianDeleteSucess {
            get {
                return ResourceManager.GetString("GuardianDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tutor atualizado com sucesso..
        /// </summary>
        public static string GuardianUpdateSucess {
            get {
                return ResourceManager.GetString("GuardianUpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de Saúde cadastrado com sucesso..
        /// </summary>
        public static string HealthPlanAddSucess {
            get {
                return ResourceManager.GetString("HealthPlanAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de Saúde apagada com sucesso..
        /// </summary>
        public static string HealthPlanDeleteSucess {
            get {
                return ResourceManager.GetString("HealthPlanDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de Saúde atualizado com sucesso..
        /// </summary>
        public static string HealthPlanUpdateSucess {
            get {
                return ResourceManager.GetString("HealthPlanUpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há fotos de pets com mais de 30 dias sem atualização..
        /// </summary>
        public static string MessegeUpdateImg {
            get {
                return ResourceManager.GetString("MessegeUpdateImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar ação.
        /// </summary>
        public static string NotificationError {
            get {
                return ResourceManager.GetString("NotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo não esperado.
        /// </summary>
        public static string NotificationTypeError {
            get {
                return ResourceManager.GetString("NotificationTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento adicionado com sucesso..
        /// </summary>
        public static string PaymentAddSuccess {
            get {
                return ResourceManager.GetString("PaymentAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento cancelado com sucesso..
        /// </summary>
        public static string PaymentDeleteSuccess {
            get {
                return ResourceManager.GetString("PaymentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pet cadastrado com sucesso..
        /// </summary>
        public static string PetAddSucess {
            get {
                return ResourceManager.GetString("PetAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pet apagado com sucesso..
        /// </summary>
        public static string PetDeleteSucess {
            get {
                return ResourceManager.GetString("PetDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pet atualizado com sucesso..
        /// </summary>
        public static string PetUpdateSucess {
            get {
                return ResourceManager.GetString("PetUpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procedimento cadastrado com sucesso..
        /// </summary>
        public static string ProcedureAddSucess {
            get {
                return ResourceManager.GetString("ProcedureAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procedimento apagado com sucesso..
        /// </summary>
        public static string ProcedureDeleteSucess {
            get {
                return ResourceManager.GetString("ProcedureDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo de procedimento cadastrado com sucesso..
        /// </summary>
        public static string ProcedureGroupAddSucess {
            get {
                return ResourceManager.GetString("ProcedureGroupAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo de procedimento apagado com sucesso..
        /// </summary>
        public static string ProcedureGroupDeleteSucess {
            get {
                return ResourceManager.GetString("ProcedureGroupDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo de procedimento atualizado com sucesso..
        /// </summary>
        public static string ProcedureGroupUpdateSucess {
            get {
                return ResourceManager.GetString("ProcedureGroupUpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vínculos do procedimento atualizados com sucesso..
        /// </summary>
        public static string ProcedureHealthPlanSuccess {
            get {
                return ResourceManager.GetString("ProcedureHealthPlanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procedimento atualizado com sucesso..
        /// </summary>
        public static string ProcedureUpdateSucess {
            get {
                return ResourceManager.GetString("ProcedureUpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espécie cadastrada com sucesso..
        /// </summary>
        public static string SpecieAddSucess {
            get {
                return ResourceManager.GetString("SpecieAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espécie apagada com sucesso..
        /// </summary>
        public static string SpecieDeleteSucess {
            get {
                return ResourceManager.GetString("SpecieDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espécie atualizada com sucesso..
        /// </summary>
        public static string SpecieUpdateSucess {
            get {
                return ResourceManager.GetString("SpecieUpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário cadastrado com sucesso..
        /// </summary>
        public static string UserAddSucess {
            get {
                return ResourceManager.GetString("UserAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário criado..
        /// </summary>
        public static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário apagado com sucesso..
        /// </summary>
        public static string UserDeleteSucess {
            get {
                return ResourceManager.GetString("UserDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login realizado com sucesso.
        /// </summary>
        public static string UserLogged {
            get {
                return ResourceManager.GetString("UserLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha atualizada com sucesso..
        /// </summary>
        public static string UserPassawordUpdate {
            get {
                return ResourceManager.GetString("UserPassawordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário atualizado com sucesso..
        /// </summary>
        public static string UserUpdateSucess {
            get {
                return ResourceManager.GetString("UserUpdateSucess", resourceCulture);
            }
        }
    }
}
