//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopCRM.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetShopCRM.Application.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clínica não encontrada..
        /// </summary>
        public static string ClinicNotFound {
            get {
                return ResourceManager.GetString("ClinicNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao atualizar configuração..
        /// </summary>
        public static string ConfigurationErrorUpdate {
            get {
                return ResourceManager.GetString("ConfigurationErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configuração atualizada com sucesso..
        /// </summary>
        public static string ConfigurationSuccessUpdate {
            get {
                return ResourceManager.GetString("ConfigurationSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha para envio de e-mail não configurado..
        /// </summary>
        public static string EmailPasswordNotFound {
            get {
                return ResourceManager.GetString("EmailPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remetente de e-mail não configurado..
        /// </summary>
        public static string EmailSenderNotFound {
            get {
                return ResourceManager.GetString("EmailSenderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail enviado com sucesso..
        /// </summary>
        public static string EmailSuccess {
            get {
                return ResourceManager.GetString("EmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário e senha para envio de e-mail não configurado..
        /// </summary>
        public static string EmailUserAndPasswordNotFound {
            get {
                return ResourceManager.GetString("EmailUserAndPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário para envio de e-mail não configurado..
        /// </summary>
        public static string EmailUserNotFound {
            get {
                return ResourceManager.GetString("EmailUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tutor não encontrado..
        /// </summary>
        public static string GuardianNotFound {
            get {
                return ResourceManager.GetString("GuardianNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na integração de pagamento..
        /// </summary>
        public static string PaymentIntegrationFailed {
            get {
                return ResourceManager.GetString("PaymentIntegrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento não encontrado..
        /// </summary>
        public static string PaymentNotFound {
            get {
                return ResourceManager.GetString("PaymentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pet não encontrado..
        /// </summary>
        public static string PetNotFound {
            get {
                return ResourceManager.GetString("PetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procedimento não encontrado..
        /// </summary>
        public static string ProcedureNotFound {
            get {
                return ResourceManager.GetString("ProcedureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espécie não encontrada..
        /// </summary>
        public static string SpecieNotFound {
            get {
                return ResourceManager.GetString("SpecieNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inválido.
        /// </summary>
        public static string UserInvalid {
            get {
                return ResourceManager.GetString("UserInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário atualizado com sucesso..
        /// </summary>
        public static string UserSucessUpdate {
            get {
                return ResourceManager.GetString("UserSucessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário válido.
        /// </summary>
        public static string UserValid {
            get {
                return ResourceManager.GetString("UserValid", resourceCulture);
            }
        }
    }
}
